app:
  nameOverride: ""         # Optional: Can be set by the user to override the app name
  fullnameOverride: ""     # Optional: Can be set by the user to override the full name of the app
  labels: {}               # Empty by default, to be filled by the user with additional labels

deployment:
  enabled: true            # User can toggle deployment on/off
  containers: []           # To be specified by the user: list of containers with image and config

service:
  enabled: false            # User can toggle service creation on/off
  type: ClusterIP          # Default service type; users can override this
  ports: []                # To be defined by the user, e.g. [{name: http, port: 80, targetPort: 8080}]

ingress:
  enabled: false           # Default to false, users can enable ingress and define their settings

hpa:
  enabled: false           # Horizontal Pod Autoscaler disabled by default
  minReplicas: 1           # Minimum number of replicas for autoscaling (default 1)
  maxReplicas: 2           # Maximum number of replicas for autoscaling (default 5)

pvc:
  enabled: false           # PVC disabled by default; users need to specify PVC details if required

pv:
  enabled: false           # PV disabled by default; users need to define PV details if required
