app:
  name: my-app
  labels:
    app.kubernetes.io/name: my-app
    app.kubernetes.io/part-of: my-project
  selectors:
    app.kubernetes.io/name: my-app
    app.kubernetes.io/instance: my-app-instance

service:
  enabled: true
  type: ClusterIP # Can be ClusterIP or NodePort
  annotations: 
    "prometheus.io/scrape": "true"
    "prometheus.io/port": "8080"
  externalTrafficPolicy: Cluster # Only used if type is NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
      nodePort: 30001 # Only used if type is NodePort

ingress:
  enabled: true
  ingressClassName: "nginx" # Optional ingress class
  annotations:
    "nginx.ingress.kubernetes.io/rewrite-target": "/"
    "cert-manager.io/cluster-issuer": "letsencrypt-prod"
  tls:
    - hosts:
        - "example.com"
      secretName: "example-com-tls"
  rules:
    - host: "example.com"
      paths:
        - path: /
          pathType: Prefix
          service:
            name: my-app-service
            port: 80
    - host: "another.com"
      paths:
        - path: /api
          pathType: Prefix
          service:
            name: another-service
            port: 8080

deployment:
  enabled: true  # Toggle for deployment
  replicas: 3
  annotations:
    "deployment.kubernetes.io/revision": "1"
  containers:
    - name: my-app-container
      image: my-app:1.0.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      env:
        - name: ENV_VAR
          value: "production"
      resources:
        limits:
          cpu: "500m"
          memory: "128Mi"
        requests:
          cpu: "200m"
          memory: "64Mi"
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
          subPath: config.yaml
  volumes:
    - name: config-volume
      configMap:
        name: my-app-config
        items:
          - key: config.yaml
            path: config.yaml

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 70
  annotations:
    "autoscaling.kubernetes.io/metrics": "cpu"
  customMetrics: 
    - type: Resource
      resource:
        name: custom_metric_name
      targetType: AverageValue
      averageValue: "100Mi"
