app:
  nameOverride: ""         # Optional: Can be set by the user to override the app name
  fullnameOverride: ""     # Optional: Can be set by the user to override the full name of the app
  labels: {}               # Empty by default, to be filled by the user with additional labels

deployment:
  enabled: true            # User can toggle deployment on/off
  containers: []           # To be specified by the user: list of containers with image and config
  deployment:
  replicas: 2
  containerPort: 80
  labels:
    environment: "production"
  image:
    repository: "nginx"
    tag: "1.21.0"
    pullPolicy: "IfNotPresent"
  env: # Environment variables for the container
    - name: "ENV"
      value: "production"

  # Optional resource limits and requests
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

  # Liveness probe configuration
  livenessProbe:
    enabled: true
    path: "/healthz"
    port: 80
    scheme: "HTTP"  # Can be set to "HTTP" or "HTTPS"
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  # Readiness probe configuration
  readinessProbe:
    enabled: true
    path: "/ready"
    port: 80
    scheme: "HTTP"  # Can be set to "HTTP" or "HTTPS"
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
    
service:
  enabled: false            # User can toggle service creation on/off
  type: ClusterIP          # Default service type; users can override this
  ports: []                # To be defined by the user, e.g. [{name: http, port: 80, targetPort: 8080}]

ingress:
  enabled: false           # Default to false, users can enable ingress and define their settings

hpa:
  enabled: false           # Horizontal Pod Autoscaler disabled by default
  minReplicas: 1           # Minimum number of replicas for autoscaling (default 1)
  maxReplicas: 2           # Maximum number of replicas for autoscaling (default 5)

pvc:
  enabled: false           # PVC disabled by default; users need to specify PVC details if required

pv:
  enabled: false           # PV disabled by default; users need to define PV details if required


pdb:
  enabled: true
  name: ""         # Optional — defaults to <release-name>-pdb
  namespace: ""    # Optional — defaults to .Release.Namespace

  labels:
    app: my-app

  annotations:
    owner: team-a

  selector:
    matchLabels:
      app: my-app

  minAvailable: 2

