app:
  name: my-app
  labels:
    app.kubernetes.io/name: my-app
    app.kubernetes.io/part-of: my-project
  selectors:
    app.kubernetes.io/name: my-app
    app.kubernetes.io/instance: my-app-instance

service:
  enabled: true
  type: ClusterIP # Can be ClusterIP or NodePort
  annotations: 
    "prometheus.io/scrape": "true"
    "prometheus.io/port": "8080"
  externalTrafficPolicy: Cluster # Only used if type is NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
      nodePort: 30001 # Only used if type is NodePort

ingress:
  enabled: true
  ingressClassName: "nginx" # Optional ingress class
  annotations:
    "nginx.ingress.kubernetes.io/rewrite-target": "/"
    "cert-manager.io/cluster-issuer": "letsencrypt-prod"
  tls:
    - hosts:
        - "example.com"
      secretName: "example-com-tls"
  rules:
    - host: "example.com"
      paths:
        - path: /
          pathType: Prefix
          service:
            name: my-app-service
            port: 80
    - host: "another.com"
      paths:
        - path: /api
          pathType: Prefix
          service:
            name: another-service
            port: 8080
