apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
    {{- range $key, $value := .Values.deployment.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        {{- range $key, $value := .Values.deployment.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:

      {{- if .Values.deployment.initContainer.enabled }}
      initContainers:
        - name: {{ .Release.Name }}-init
          image: {{ .Values.deployment.initContainer.image.repository }}:{{ .Values.deployment.initContainer.image.tag | default "latest" }}
          imagePullPolicy: {{ .Values.deployment.initContainer.image.pullPolicy | default "IfNotPresent" }}
          {{- if .Values.deployment.initContainer.command }}
          command:
            {{- range .Values.deployment.initContainer.command }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.deployment.initContainer.args }}
          args:
            {{- range .Values.deployment.initContainer.args }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.deployment.initContainer.env }}
          env:
            {{- range .Values.deployment.initContainer.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.deployment.initContainer.resources }}
          resources:
            {{- toYaml .Values.deployment.initContainer.resources | nindent 12 }}
          {{- end }}
      {{- end }}

      containers:
        - name: {{ .Release.Name }}-container
          image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default "latest" }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort | default 80 }}
          {{- if .Values.deployment.env }}
          env:
            {{- range .Values.deployment.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}

          {{- if .Values.deployment.resources }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          {{- end }}

          {{- if .Values.deployment.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.livenessProbe.path | default "/" }}
              port: {{ .Values.deployment.livenessProbe.port | default 80 }}
              scheme: {{ .Values.deployment.livenessProbe.scheme | default "HTTP" }}
            initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds | default 5 }}
            failureThreshold: {{ .Values.deployment.livenessProbe.failureThreshold | default 3 }}
            successThreshold: {{ .Values.deployment.livenessProbe.successThreshold | default 1 }}
          {{- end }}

          {{- if .Values.deployment.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.readinessProbe.path | default "/" }}
              port: {{ .Values.deployment.readinessProbe.port | default 80 }}
              scheme: {{ .Values.deployment.readinessProbe.scheme | default "HTTP" }}
            initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds | default 5 }}
            periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds | default 5 }}
            failureThreshold: {{ .Values.deployment.readinessProbe.failureThreshold | default 3 }}
            successThreshold: {{ .Values.deployment.readinessProbe.successThreshold | default 1 }}
          {{- end }}
