{{- if .Values.pdb.enabled }}

{{- $pdb := .Values.pdb }}
{{- $name := $pdb.name | default (printf "%s-pdb" .Release.Name) }}
{{- $namespace := $pdb.namespace | default .Release.Namespace }}
{{- $labels := $pdb.labels | default dict }}
{{- $annotations := $pdb.annotations | default dict }}

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name | quote }}
  namespace: {{ $namespace | quote }}
  {{- if $labels }}
  labels:
    {{- toYaml $labels | nindent 4 }}
  {{- end }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- toYaml ($pdb.selector.matchLabels | default dict) | nindent 6 }}
  {{- if hasKey $pdb "minAvailable" }}
  minAvailable: {{ $pdb.minAvailable }}
  {{- else if hasKey $pdb "maxUnavailable" }}
  maxUnavailable: {{ $pdb.maxUnavailable }}
  {{- else }}
  minAvailable: 1
  {{- end }}

{{- end }}
