{{- if .Values.persistentVolume.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
  labels:
    app: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.size }}
  accessModes:
  - {{ .Values.persistentVolume.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolume.reclaimPolicy }}
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  {{- if eq .Values.persistentVolume.type "nfs" }}
  nfs:
    server: {{ .Values.persistentVolume.nfs.server }}
    path: {{ .Values.persistentVolume.nfs.path }}
  {{- else if eq .Values.persistentVolume.type "hostPath" }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath.path }}
    type: {{ .Values.persistentVolume.hostPath.type | default "DirectoryOrCreate" }}
  {{- else if eq .Values.persistentVolume.type "efs" }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.persistentVolume.efs.fileSystemId }}
    {{- if .Values.persistentVolume.efs.accessPointId }}
    volumeAttributes:
      accessPointId: {{ .Values.persistentVolume.efs.accessPointId }}
    {{- end }}
  {{- end }}
---
{{- end -}}
