{{- if .Values.serviceAccount.enabled }}

{{- $sa := .Values.serviceAccount }}
{{- $name := $sa.name | default (printf "%s-sa" .Release.Name) }}
{{- $namespace := $sa.namespace | default .Release.Namespace }}
{{- $labels := $sa.labels | default dict }}
{{- $annotations := $sa.annotations | default dict }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name | quote }}
  namespace: {{ $namespace | quote }}
  {{- if $labels }}
  labels:
    {{- toYaml $labels | nindent 4 }}
  {{- end }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
{{- if or $sa.imagePullSecrets $sa.secrets }}
imagePullSecrets:
  {{- range $secret := $sa.imagePullSecrets }}
  - name: {{ $secret.name | quote }}
  {{- end }}
{{- end }}
{{- if $sa.secrets }}
secrets:
  {{- range $secret := $sa.secrets }}
  - name: {{ $secret.name | quote }}
  {{- end }}
{{- end }}

{{- end }}
