{{- if .Values.serviceAccount.enabled }}
{{- $commonAnnotations := .Values.serviceAccount.annotations | default dict }}
{{- $commonLabels := .Values.serviceAccount.labels | default dict }}
{{- $saList := .Values.serviceAccount.list | default list }}

{{- range $index, $sa := $saList }}
{{- $saName := $sa.name }}
{{- if or (not $saName) (eq $saName "") }}
  {{- $saName = printf "%s-sa-%d" $.Release.Name $index }}
{{- end }}

{{- $saNamespace := $sa.namespace }}
{{- if or (not $saNamespace) (eq $saNamespace "") }}
  {{- $saNamespace = $.Release.Namespace }}
{{- end }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName | quote }}
  namespace: {{ $saNamespace | quote }}
  labels:
    {{- $mergedLabels := mergeOverwrite (deepCopy $commonLabels) ($sa.labels | default dict) }}
    {{- toYaml $mergedLabels | nindent 4 }}
  annotations:
    {{- $mergedAnnotations := mergeOverwrite (deepCopy $commonAnnotations) ($sa.annotations | default dict) }}
    {{- toYaml $mergedAnnotations | nindent 4 }}
{{- if hasKey $sa "automountServiceAccountToken" }}
automountServiceAccountToken: {{ $sa.automountServiceAccountToken }}
{{- end }}
{{- if $sa.imagePullSecrets }}
imagePullSecrets:
  {{- range $secret := $sa.imagePullSecrets }}
  - name: {{ $secret | quote }}
  {{- end }}
{{- end }}

---
{{- end }}
{{- end }}
